# Generated by Django 5.1.2 on 2024-12-23 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0003_rename_meal_name_foodlog_food_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlog',
            old_name='food_name',
            new_name='meal_name',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
