# Generated by Django 5.1.2 on 2024-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0004_rename_food_name_foodlog_meal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
    ]
