# Generated by Django 5.1.2 on 2024-12-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0005_foodlog_fats_foodlog_protein_alter_foodlog_calories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='carbs_goal',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('exercise_level', models.CharField(blank=True, choices=[('none', 'No Exercise'), ('light', 'Light Exercise'), ('moderate', 'Moderate Exercise'), ('intense', 'Intense Exercise')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
