# Generated by Django 5.1.2 on 2024-12-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0006_remove_goal_carbs_goal_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='calorie_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='fats_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='protein_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='water_goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('reduce', 'Reduce Weight'), ('maintain', 'Maintain Weight'), ('increase', 'Increase Calories')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
